// <auto-generated />
using System;
using EcoMeal.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoMeal.DataAccess.Migrations
{
    [DbContext(typeof(EcoMealDbContext))]
    [Migration("20260707135252_SeedDataValues")]
    partial class SeedDataValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("BusinessTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTypeId");

                    b.ToTable("Business", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Address = "Str. Victoriei, Nr. 10",
                            BusinessTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "A cozy place with sustainable and delicious food.",
                            ImageUrl = "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
                            Name = "Green Bite Bistro"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Address = "Str. Libertății, Nr. 5",
                            BusinessTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Your local supermarket for fresh produce and essentials.",
                            ImageUrl = "https://images.unsplash.com/photo-1586201375761-83865001e3b6",
                            Name = "FreshMart"
                        });
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.BusinessType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BusinessType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Supermarket"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Bakery"
                        });
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.OrderPackage", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("OrderPackage", (string)null);
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PackageTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PickupEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PickupStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("PackageTypeId");

                    b.ToTable("Package", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BusinessId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Delicious leftover meals perfectly fine to eat.",
                            ImageUrl = "https://images.unsplash.com/photo-1542838132-92c53300491e",
                            Name = "End of Day Surprise",
                            PackageTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PickupEnd = new DateTime(2026, 7, 8, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            PickupStart = new DateTime(2026, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 15.5m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BusinessId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Perfect for toast, sandwiches or making breadcrumbs.",
                            ImageUrl = "https://images.unsplash.com/photo-1509440159596-0249088772ff",
                            Name = "Yesterday's Bread Bundle",
                            PackageTypeId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PickupEnd = new DateTime(2026, 7, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PickupStart = new DateTime(2026, 7, 8, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3.5m,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.PackageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PackageType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Surprise Bag"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Pastry Bag"
                        });
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Business", b =>
                {
                    b.HasOne("EcoMeal.DataAccess.Entities.BusinessType", "BusinessType")
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Order", b =>
                {
                    b.HasOne("EcoMeal.DataAccess.Entities.Business", "Business")
                        .WithMany("Orders")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoMeal.DataAccess.Entities.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoMeal.DataAccess.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.OrderPackage", b =>
                {
                    b.HasOne("EcoMeal.DataAccess.Entities.Order", "Order")
                        .WithMany("OrderPackages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EcoMeal.DataAccess.Entities.Package", "Package")
                        .WithMany("OrderPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Package", b =>
                {
                    b.HasOne("EcoMeal.DataAccess.Entities.Business", "Business")
                        .WithMany("Packages")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoMeal.DataAccess.Entities.PackageType", "PackageType")
                        .WithMany("Packages")
                        .HasForeignKey("PackageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("PackageType");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.User", b =>
                {
                    b.HasOne("EcoMeal.DataAccess.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Business", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.BusinessType", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Order", b =>
                {
                    b.Navigation("OrderPackages");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Package", b =>
                {
                    b.Navigation("OrderPackages");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.PackageType", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EcoMeal.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
